### ISSUE TITLE
Custom Banks 2-4 not working as expected

### ISSUE THREAD

**Issue by Dipe22** [dozius/TwisterSister#11]
Hey hey first and foremost thank you for this awesome script. Just got my Midi Twister and its amazing.

I tried to use the Banks 2-4 but it seems that the encoders behave the same like in bank 1. The first one still selects tracks etc.
The only thing that changes is that the color switched from the track color to white but they are not free for mapping.

I am using the new Bitwig 5 Beta but it also didnt work here in the last 4.9.

Is there anything i missed during the installation ??

Again thank u very much for this :)
Benjamin

**Comment by dozius** [comment]
Sounds like your device is not configured correctly. Make sure you are following the installation instructions.

https://github.com/dozius/TwisterSister/blob/main/docs/README.md#installation

**Comment by Dipe22** [comment]
Hey man,  sry to bother you. :/ i tried the installation process multiple times however without changing the behaviour of the 2nd-4th bank. Is there anything else i can try?

**Comment by dozius** [comment]
Still sounds like your device configuration is messed up.

Please provide the following information:

OS: [e.g. Windows]
Bitwig Version: [e.g. 4.4.10]
Extension Version: [e.g. 2.0.0]
Device Firmware: [e.g. 02 Oct 2019]
MIDI Fighter Utility Version: [e.g. 2.85]

I suggest making sure your device has the latest firmware, then doing a factory reset before loading the mfs that comes with the extension. If you are still experiencing issues after doing this then please export your device settings from the MIDI fighter utility and upload them here.

**Comment by Dipe22** [comment]
Thank you so much for the help! I already tried the factory reset, deinstalling other controllers in Bitwig  and using another usb ports for the MF. I really have no clue what causes this behaviour :/ 

My Specs:
OS: Windows 10
Bitwig Version: tested with 4.4.9 and 5.0 beta 3
Extension Version: e.g. 2.0.1
Device Firmware: 02 Oct 2019
MIDI Fighter Utility Version: e.g. 2.85

[Exported MF Settings.zip](https://github.com/dozius/TwisterSister/files/11257852/Exported.MF.Settings.zip)

[MF Bug Video.zip](https://github.com/dozius/TwisterSister/files/11257879/MF.Bug.Video.zip)

**Comment by dozius** [comment]
This is definitely some kind of issue with your device. The settings backup you uploaded doesn't match the one provided by the extension. The only way the other banks would act like the first bank is if they were configured incorrectly or outputting the wrong MIDI data.

Looks like it might be this issue. https://forum.djtechtools.com/showthread.php?t=92596&page=2 

The description fits the behaviour you are seeing. You could confirm by monitoring the MIDI output from the device. Apparently reloading the firmware will fix the messed up encoder behaviour.

Anyways, since this is certainly an issue with your device and not the extension I'll have to leave it to you to figure this one out on your own. I'm not doing free tech support for DJ Techtools. I hope you understand my position and good luck! 😅
