### ISSUE TITLE
Question re: pinned indicator

### ISSUE THREAD

**Issue by pschuegr** [dozius/TwisterSister#6]
First of all, thanks for this, it's amazing.  I just got an MFT and was resigning myself to building something, this is way better than I would have done.  

Question re: the pinned indicator.  I couldn't find something explaining what exactly this does, but it seems to me that when something is pinned, it keeps the UI focus even though the MFT can still control other tracks/devices.  Is that right?  Happy to submit a PR to document this if that's correct.

Cheers

**Comment by dozius** [comment]
Great, happy to hear you are finding it useful!

Cursor pinning is a common feature of Bitwig API. You can see the cursors for each controller in the studio I/O panel. When a cursor is pinned, it no longer follows the UI selection. This is useful if you want to, for example, have the MFT controlling a channel or device that is different from what you have selected in the UI. It's also handy when you have multiple controllers because they can be targeted independently of the UI selection and each other.

Not sure it needs to be documented here, since this is a common feature of the Bitwig API itself, but I certainly wouldn't turn down a pull request with well written documentation for the feature.

**Comment by pschuegr** [comment]
Ok, thanks for the explanation.  I can see now that when I pin a track with the MFT, and I then select something with the UI, I can still control that track.  What I'm still a bit unclear about is: if I pin something with the MFT (or using the pin button on the MFT cursor in the studio panel), but then I continue to "scroll" through tracks using the MFT knob 1, I'm not sure exactly what's happening - it seems like I'm now changing what is pinned? Like once I enter "pinned" mode, I've essentially separated the UI selection from the MFT controls, and now I can change the MFT pinned track independently?  When I leave pinned mode I am re-unifying the UI and MFT selected track?

This seems to be what is happening, but it's really not how the normal conventions of "pinning" in a UI work (this is not a complaint directed at you or anybody in particular, just feels like maybe pinning isn't quite the right name for this behavior).  I'd expect something that is pinned to stay put until it's un-pinned, I think.

It might be worth documenting since AFAIK this cursor concept isn't really mentioned in the main Bitwig manual.  Although really it probably should be.

**Comment by dozius** [comment]
Yeah, sounds like you got it. The pinned state for a cursor is really just "This cursor is no longer following other cursors".

I agree, the documentation for Bitwig is still lacking in a number of areas. The extension API docs are even worse. 😉 I don't know when I will have time to update this extensions docs with info on pinning, but like I said earlier, I wouldn't turn down a well written patch to the docs.
